#!/usr/bin/env python3
"""Inventory audit.

Walks the probe-log corpus and the cloud-dump corpus and reports any
slot, event, CFG key, or cfg_individual endpoint that isn't represented
in inventory.yaml.

Exit code 0: every observation is accounted for.
Exit code 1: at least one observation is missing from the inventory.
Exit code 2: usage error.

Outputs:
- stdout: human-readable report
- writes docs/research/inventory/generated/coverage-report.md
"""
from __future__ import annotations

import argparse
import glob
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INVENTORY = REPO_ROOT / "docs" / "research" / "inventory" / "inventory.yaml"
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "research" / "inventory" / "generated" / "coverage-report.md"

_BANNER = (
    "<!-- DO NOT EDIT BY HAND. Generated by tools/inventory_audit.py. -->\n\n"
)


def _index_inventory(inv: dict[str, Any]) -> dict[str, set[str]]:
    """Return a {section_name: set_of_ids} index for fast lookup."""
    out: dict[str, set[str]] = defaultdict(set)
    for section in (
        "properties", "events", "actions", "opcodes",
        "cfg_keys", "cfg_individual",
    ):
        for row in inv.get(section) or []:
            rid = row.get("id")
            if rid is not None:
                out[section].add(str(rid))
    return out


def _walk_probe_logs(probe_glob: str) -> dict[tuple[str, int, int], int]:
    """Return {(kind, siid, key): count}; kind = 'property' or 'event'."""
    seen: dict[tuple[str, int, int], int] = defaultdict(int)
    for path in glob.glob(probe_glob):
        if path == "/dev/null":
            continue
        with open(path) as f:
            for raw_line in f:
                line = raw_line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                except json.JSONDecodeError:
                    continue
                parsed = rec.get("parsed_data") or {}
                method = parsed.get("method")
                params = parsed.get("params")
                if not isinstance(params, list):
                    continue
                for p in params:
                    if not isinstance(p, dict):
                        continue
                    siid = p.get("siid")
                    if siid is None:
                        continue
                    if method == "properties_changed" and "piid" in p:
                        seen[("property", int(siid), int(p["piid"]))] += 1
                    elif method == "event_occured" and "eiid" in p:
                        seen[("event", int(siid), int(p["eiid"]))] += 1
    return seen


def _walk_cloud_dumps(dump_glob: str) -> dict[str, set[str]]:
    """Return {'cfg_keys': {...}, 'cfg_individual': {...}, 'candidates': {...}}."""
    out: dict[str, set[str]] = {
        "cfg_keys": set(),
        "cfg_individual": set(),
        "candidates": set(),
    }
    for path in glob.glob(dump_glob):
        if path == "/dev/null":
            continue
        try:
            data = json.loads(Path(path).read_text())
        except (json.JSONDecodeError, FileNotFoundError):
            continue
        cfg = data.get("cfg_full") or data.get("cfg") or {}
        if isinstance(cfg, dict):
            out["cfg_keys"].update(str(k) for k in cfg.keys())
        cfg_indiv = data.get("cfg_individual") or {}
        if isinstance(cfg_indiv, dict):
            out["cfg_individual"].update(str(k) for k in cfg_indiv.keys())
        cands = data.get("candidates") or {}
        if isinstance(cands, dict):
            out["candidates"].update(str(k) for k in cands.keys())
    return out


def _format_id(kind: str, siid: int, key: int) -> str:
    if kind == "property":
        return f"s{siid}p{key}"
    return f"event_s{siid}eiid{key}"


def audit(
    inventory: dict[str, Any],
    probe_glob: str,
    dump_glob: str,
) -> tuple[int, str]:
    """Run the audit and return (exit_code, markdown_report)."""
    indexed = _index_inventory(inventory)
    probe = _walk_probe_logs(probe_glob)
    dumps = _walk_cloud_dumps(dump_glob)

    missing_props: list[tuple[str, int]] = []
    missing_events: list[tuple[str, int]] = []
    for (kind, siid, key), count in sorted(probe.items()):
        rid = _format_id(kind, siid, key)
        target = "properties" if kind == "property" else "events"
        if rid not in indexed[target]:
            (missing_props if kind == "property" else missing_events).append((rid, count))

    missing_cfg_keys = sorted(dumps["cfg_keys"] - indexed["cfg_keys"])
    missing_cfg_indiv = sorted(dumps["cfg_individual"] - indexed["cfg_individual"])
    missing_cands = sorted(dumps["candidates"] - indexed["cfg_individual"])

    report: list[str] = [_BANNER, "# Coverage Report\n\n"]
    any_missing = False

    def section(title: str, items: list[Any]) -> None:
        nonlocal any_missing
        report.append(f"## {title}\n\n")
        if not items:
            report.append("_(empty — all accounted for)_\n\n")
            return
        any_missing = True
        for it in items:
            report.append(f"- {it}\n")
        report.append("\n")

    section(
        "Probe-log properties not in inventory",
        [f"`{rid}` (×{count})" for rid, count in missing_props],
    )
    section(
        "Probe-log events not in inventory",
        [f"`{rid}` (×{count})" for rid, count in missing_events],
    )
    section("Cloud-dump CFG keys not in inventory", [f"`{k}`" for k in missing_cfg_keys])
    section("Cloud-dump cfg_individual endpoints not in inventory", [f"`{k}`" for k in missing_cfg_indiv])
    section(
        "Cloud-dump 'candidates' probes not in cfg_individual inventory",
        [f"`{k}`" for k in missing_cands],
    )

    return (1 if any_missing else 0, "".join(report))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--inventory", type=Path, default=DEFAULT_INVENTORY)
    parser.add_argument(
        "--probe-glob", type=str,
        default=str(REPO_ROOT.parent / "probe_log_*.jsonl"),
    )
    parser.add_argument(
        "--cloud-dump-glob", type=str,
        default=str(REPO_ROOT.parent / "dreame_cloud_dumps" / "dump_*.json"),
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)

    try:
        inventory = yaml.safe_load(args.inventory.read_text()) or {}
    except FileNotFoundError:
        print(f"error: {args.inventory} not found", file=sys.stderr)
        return 2

    exit_code, report = audit(inventory, args.probe_glob, args.cloud_dump_glob)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report)
    print(report)
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
